baseURL = "http://superdanby.github.io/Blog"
languageCode = "en-us"
title = "Yee"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "↩"
uglyurls = true
preserveTaxonomyNames = true
googleAnalytics = "UA-116389618-1"

[params]
    avatar = "abouts/me.gif"
