baseURL = "https://superdanby.github.io/Blog"
languageCode = "en-us"
title = "Superdanby"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "↩"
uglyurls = true
preserveTaxonomyNames = true
googleAnalytics = "UA-116389618-1"
disqusShortName = "superdanby-blog"

[params]
    avatar = "abouts/me.gif"
	anchor = true
	author = "Superdanby"
